config/routes.rb
Rails.application.routes.draw do
  resources :leaderboards
  resources :listings
  root to: 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :portfolio_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @user = User.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  @user = User.all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<header>
  <h1>Invest $3 million. Your way.</h1>
</header>
<section>

    <a href="<%= listings_path %>" title="" class="rui-button-basic-light">
      Welcome , let's play!
    </a>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>

  <link rel="stylesheet" type="text/css" href="//s1.rui.au.reastatic.net/rui-1.7.5/css/rui-all.min.css">
  <script src="//s1.rui.au.reastatic.net/rui-1.7.5/js/rui-all.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<h1>Test</h1>

<% @user.each do |user| %>
  <h1><%= user.username %></h1>
<% end %>